### ISSUE TITLE
Possibility of supporting JSON Creation Functions?

### ISSUE THREAD

**Issue by i-tu** [akheron/sqltyper#22]
First of all, thanks for your work on this library!

I noticed that there is no support for [PostgreSQL JSON Creation Functions](https://www.postgresql.org/docs/12/functions-json.html#FUNCTIONS-JSON-CREATION-TABLE) , which I use quite heavily in my use case, `row_to_json` in particular. Is there any possibility of getting those, and can I help in some way to make it happen?

**Comment by akheron** [comment]
It's as easy as determining how they behave when their argument is NULL, and adding a corresponding entry to `src/constants.ts`.

The possible NULL behaviors are documented in the same file: https://github.com/akheron/sqltyper/blob/master/src/constants.ts#L68

It would be easiest for me if you could open a PR that adds all the funcs you need.

**Comment by i-tu** [comment]
Alright! I'll take a crack at it next weekend
