### ISSUE TITLE
Warning thrown when window functions are used

### ISSUE THREAD

**Issue by shiro** [akheron/sqltyper#27]
Hello,
I got the following warning:
```
Starting compilation...
WARNING: The internal SQL parser failed to parse the SQL statement.

Parse error: Expect the end of source at (1:22)

    1| SELECT count(*) OVER ()::integer      total_rows
                            ^

Due to the problems listed above, the inferred types may be inaccurate with respect to nullability.
```
The warning seems to be thrown by the window function (`OVER ()`).
I did set the type of the over function explicitly to `integer` since it gets picked up as a string in the TS definitions otherwise.

Here's the full query:
```
SELECT count(*) OVER ()::integer      total_rows
FROM materialized_rwm;
```

Thanks for the awesome work, hope this helps.

**Comment by akheron** [comment]
Thanks! I'll have a look.

**Comment by akheron** [comment]
Fixed!
