### ISSUE TITLE
Not-nullable fields in materialized view

### ISSUE THREAD

**Issue by shiro** [akheron/sqltyper#29]
In order for the TS types to not be marked as nullable the table constraints are looked up as far as I understand.
However when dealing with materialized views there is no way to mark a field as non-nullable.

I understand that there is no way to guarantee that there is no null values in the materialized view, however as a developer I often know that based on how the view is generated.

I just wanted to ask if there is any way to mark a field as not nullable explicitly rather than relying on the DB introspection, since it means I have to manually rewrite most type definitions on materialized views which makes the use of this tool pointless for the use-case.

Thanks for the help.

**Comment by akheron** [comment]
Good point! Currently there’s no way to override what sqltyper has inferred. What do you think would be the best way mark the fields non-billable?

**Comment by shiro** [comment]
I don't know of any way to annotate selected fields using PostgreSQL's syntax.
There's probably not that many ways to do it, pretty much the only way I can think of is putting a code block in front of the SQL statement and annotate types in some way (like a docblock for example).

For example:
```
-- @type a NOT NULL
-- @type b integer NOT NULL
SELECT a, b, c FROM t;
```

Would allow to keep `a`'s inferred type and just modify nullability constraints while staying flexible about future explicit type modification such as setting the type explicitly as well.
It's just a suggestion, that or any other way would work IMO.

**Comment by akheron** [comment]
Seems you can get the underlying query of a (materialized) view, at least using the `pg_get_viewdef` function, and so it would be possible to run the analysis on that query instead.

**Comment by akheron** [comment]
Created a new issue to track this: #43
